### ISSUE TITLE
500 Error on JWKS.Endpoint.

### ISSUE THREAD

**Issue by samysousa** [angusmillar/SmartHealthCard#3]
Not sure why this is giving an error.
Created keys with OpenSSL, exported as .pfx and imported.
Additionally had to import the pfx to "Trusted Root" (This is not specified in the SSL instructions provided).

Able to get the Certificate by Thumbprint.
But once it start reading certificate i get this. 

`Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions)
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider)
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at Internal.Cryptography.Pal.CertificatePal.GetECDsaPrivateKey()
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.GetECDsaPrivateKey(X509Certificate2 certificate)
   at SmartHealthCard.Token.Algorithms.ES256Algorithm.GetPrivateKey(X509Certificate2 cert) in E:\SmartHealthCard-1.0.1\SmartHealthCard.Token\Algorithms\ES256Algorithm.cs:line 102
   at SmartHealthCard.Token.Algorithms.ES256Algorithm..ctor(X509Certificate2 Certificate, IJsonSerializer JsonSerializer) in E:\SmartHealthCard-1.0.1\SmartHealthCard.Token\Algorithms\ES256Algorithm.cs:line 24
   at SmartHealthCard.Token.SmartHealthCardJwks.GetJsonWebKeySet(IEnumerable`1 CertificateList) in E:\SmartHealthCard-1.0.1\SmartHealthCard.Token\SmartHealthCardJWKS.cs:line 48
   at SmartHealthCard.Token.SmartHealthCardJwks.Get(IEnumerable`1 CertificateList, Boolean Minified) in E:\SmartHealthCard-1.0.1\SmartHealthCard.Token\SmartHealthCardJWKS.cs:line 78
   at SmartHealthCard.JwksEndpoint.JwksSupport.JwksJsonProvider.GetJwksJson() in E:\SmartHealthCard-1.0.1\SmartHealthCard.JwksEndpoint\JwksSupport\JwksJsonProvider.cs:line 44
   at SmartHealthCard.JwksEndpoint.Controllers.JwksController.Get() in E:\SmartHealthCard-1.0.1\SmartHealthCard.JwksEndpoint\Controllers\JwksController.cs:line 26
   at lambda_method3(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.9\Microsoft.AspNetCore.Http.Extensions.dll'. Symbols loaded.`

**Comment by angusmillar** [comment]
Hi @samysousa, Sorry to hear you are having difficulties here. 
Have you given the windows account that you are running the application under permission to access the private key?

![image](https://user-images.githubusercontent.com/13332180/132475130-74b44d7a-1ca2-49ab-bbda-232ee18e109c.png)

![image](https://user-images.githubusercontent.com/13332180/132475026-1dffb53a-d9df-4745-84a7-73e064a6caca.png)

**Comment by angusmillar** [comment]
Hi @samysousa, I am going to close this issue now. I replicated the same issue you had and have explained how it is resolved above. If you feel I have not resolved it then please feel free to open the ticket again.

**Comment by samysousa** [comment]
Hi @angusmillar , 
Thanks for this, it works. 
It was indeed a security allowance issue. 
Odd however, as i use a Local account that is Local Administrator as well. 
Administrators "Have" already Full control in permissions, Yet still adding my User Account was necesary.

I suppose if you want this to run in a Public/Production environment you need to add the IIS_USERS user as well, it would run anonymously for all users in this case.

Either way, It worked. 
So it is noted that some security validations are needed at the Local Certificate level to allow this to function properly. 

Thanks.
